import { Reel, ReelAnalysis } from "@/types";

export const DETERMINISTIC_REEL_ANALYSIS: Record<string, ReelAnalysis> = {
  "reel-1": {
    reelId: "reel-1",
    primaryTopic: "Java",
    secondaryTopics: ["Programming", "Developer Humor"],
    intent: "Entertainment",
    context: "User watched a humorous clip about Java code execution succeeding.",
    difficulty: "Beginner",
    technologyDomain: "Software Engineering",
    educationalValue: 0.45,
    careerRelevance: 0.75,
    hypeScore: 0.05,
  },
  "reel-2": {
    reelId: "reel-2",
    primaryTopic: "Developer Lifestyle",
    secondaryTopics: ["Software Engineering", "Programming Career"],
    intent: "Career Guidance",
    context: "A daily vlog detailing software engineer workflows, standups, and tooling.",
    difficulty: "Beginner",
    technologyDomain: "Software Engineering",
    educationalValue: 0.65,
    careerRelevance: 0.90,
    hypeScore: 0.10,
  },
  "reel-3": {
    reelId: "reel-3",
    primaryTopic: "Coding Interviews",
    secondaryTopics: ["DSA", "Software Engineering"],
    intent: "Entertainment",
    context: "Humorous breakdown of difficult data structures and algorithm interview questions.",
    difficulty: "Intermediate",
    technologyDomain: "Software Engineering",
    educationalValue: 0.60,
    careerRelevance: 0.88,
    hypeScore: 0.08,
  },
  "reel-4": {
    reelId: "reel-4",
    primaryTopic: "Developer Hardware",
    secondaryTopics: ["Laptop", "Development", "Programming"],
    intent: "Educational",
    context: "Detailed comparison of M-series MacBooks vs Windows laptops for compilation and dev setup.",
    difficulty: "Beginner",
    technologyDomain: "Software Engineering",
    educationalValue: 0.85,
    careerRelevance: 0.80,
    hypeScore: 0.06,
  },
  "reel-5": {
    reelId: "reel-5",
    primaryTopic: "Gaming PC Setup",
    secondaryTopics: ["Gaming", "PC", "RGB"],
    intent: "Entertainment",
    context: "Showcase of RGB lighting, custom desktop PCs, and gaming peripherals.",
    difficulty: "Beginner",
    technologyDomain: "Consumer Hardware / Gaming",
    educationalValue: 0.20,
    careerRelevance: 0.15,
    hypeScore: 0.25,
  },
  "reel-6": {
    reelId: "reel-6",
    primaryTopic: "AI Job Promises",
    secondaryTopics: ["AI", "Career", "Job Search"],
    intent: "Hype/Clickbait",
    context: "Exaggerated claims promising instant software engineering jobs by using 10 AI tools.",
    difficulty: "Beginner",
    technologyDomain: "Artificial Intelligence",
    educationalValue: 0.22,
    careerRelevance: 0.30,
    hypeScore: 0.91,
  },
  "reel-7": {
    reelId: "reel-7",
    primaryTopic: "Cybersecurity DDoS",
    secondaryTopics: ["Cybersecurity", "Networking", "DDoS"],
    intent: "Educational",
    context: "Technical overview of Distributed Denial of Service attack vectors and mitigation.",
    difficulty: "Intermediate",
    technologyDomain: "Cybersecurity",
    educationalValue: 0.88,
    careerRelevance: 0.82,
    hypeScore: 0.05,
  },
  "reel-8": {
    reelId: "reel-8",
    primaryTopic: "Cloud Computing",
    secondaryTopics: ["AWS", "Software Engineering", "Career"],
    intent: "Educational",
    context: "Explanation of cloud infrastructure role in modern backend web software development.",
    difficulty: "Intermediate",
    technologyDomain: "Cloud Computing",
    educationalValue: 0.89,
    careerRelevance: 0.92,
    hypeScore: 0.05,
  },
};

export function analyzeReel(reel: Reel): ReelAnalysis {
  if (DETERMINISTIC_REEL_ANALYSIS[reel.id]) {
    return DETERMINISTIC_REEL_ANALYSIS[reel.id];
  }
  
  return {
    reelId: reel.id,
    primaryTopic: reel.topics[0] || "General Tech",
    secondaryTopics: reel.topics.slice(1),
    intent: "Educational",
    context: `Analysis for ${reel.title}`,
    difficulty: "Beginner",
    technologyDomain: "Software Engineering",
    educationalValue: 0.70,
    careerRelevance: 0.75,
    hypeScore: 0.10,
  };
}
